server:
  port: 8777
  tomcat:
    uri-encoding: UTF-8

#阅读，收藏，点赞，评论，分享,，关注，留言

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/run_chen_blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 3
      maximum-pool-size: 3
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  mvc:
    dispatch-options-request: true

mybatis:
  type-aliases-package: com.cg.entity.po
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

